services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: healthcare_db
    ports:
      - "5432:5432"
    # This forces the Postgres process itself to initialize using Kolkata
    command: ["postgres", "-c", "timezone=Asia/Kolkata"]
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: